export enum Permission {
  USER_READ = "USER_READ",
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",

  COURSE_READ = "COURSE_READ",
  COURSE_CREATE = "COURSE_CREATE",
  COURSE_UPDATE = "COURSE_UPDATE",
  COURSE_DELETE = "COURSE_DELETE",

  MODULE_CREATE = "MODULE_CREATE",
  MODULE_UPDATE = "MODULE_UPDATE",
  MODULE_DELETE = "MODULE_DELETE",

  LESSON_CREATE = "LESSON_CREATE",
  LESSON_UPDATE = "LESSON_UPDATE",
  LESSON_DELETE = "LESSON_DELETE",

  RESOURCE_UPLOAD = "RESOURCE_UPLOAD",
  RESOURCE_DELETE = "RESOURCE_DELETE",

  CERTIFICATE_GENERATE = "CERTIFICATE_GENERATE",
  CERTIFICATE_VERIFY = "CERTIFICATE_VERIFY",

  PAYMENT_VIEW = "PAYMENT_VIEW",
  PAYMENT_MANAGE = "PAYMENT_MANAGE",

  ANALYTICS_VIEW = "ANALYTICS_VIEW",
  AUDIT_VIEW = "AUDIT_VIEW",

  SYSTEM_ADMIN = "SYSTEM_ADMIN",
}
