import { Permission } from "./permissions";

export const RolePermissions: Record<string, Permission[]> = {
  Admin: [
    Permission.SYSTEM_ADMIN,
    Permission.USER_READ,
    Permission.USER_CREATE,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.COURSE_READ,
    Permission.COURSE_CREATE,
    Permission.COURSE_UPDATE,
    Permission.COURSE_DELETE,
    Permission.MODULE_CREATE,
    Permission.MODULE_UPDATE,
    Permission.MODULE_DELETE,
    Permission.LESSON_CREATE,
    Permission.LESSON_UPDATE,
    Permission.LESSON_DELETE,
    Permission.RESOURCE_UPLOAD,
    Permission.RESOURCE_DELETE,
    Permission.CERTIFICATE_GENERATE,
    Permission.CERTIFICATE_VERIFY,
    Permission.PAYMENT_VIEW,
    Permission.PAYMENT_MANAGE,
    Permission.ANALYTICS_VIEW,
    Permission.AUDIT_VIEW,
  ],
  Instructor: [
    Permission.COURSE_READ,
    Permission.COURSE_CREATE,
    Permission.COURSE_UPDATE,
    Permission.COURSE_DELETE,
    Permission.MODULE_CREATE,
    Permission.MODULE_UPDATE,
    Permission.MODULE_DELETE,
    Permission.LESSON_CREATE,
    Permission.LESSON_UPDATE,
    Permission.LESSON_DELETE,
    Permission.RESOURCE_UPLOAD,
    Permission.RESOURCE_DELETE,
    Permission.ANALYTICS_VIEW,
  ],
  Mentor: [
    Permission.COURSE_READ,
    Permission.ANALYTICS_VIEW,
  ],
  Student: [
    Permission.COURSE_READ,
    Permission.CERTIFICATE_VERIFY,
  ],
};
